services:
  kpfc:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    volumes:
      - dbdata:/data
      - mediadata:/media
    restart: unless-stopped

volumes:
  dbdata:
  mediadata:
